// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIDPdibOxjlArEPodnSgTpswkciUoxU7E',
    appId: '1:1073665114674:web:1ec7ad54f0159e5816b22b',
    messagingSenderId: '1073665114674',
    projectId: 'leafyyy-6ccee',
    authDomain: 'leafyyy-6ccee.firebaseapp.com',
    storageBucket: 'leafyyy-6ccee.appspot.com',
    measurementId: 'G-K10DWLV9MC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_EQBSc7tT4QZi5BIMNk2f9nxZLGRt-to',
    appId: '1:1073665114674:android:b5cfe90b327cf95216b22b',
    messagingSenderId: '1073665114674',
    projectId: 'leafyyy-6ccee',
    storageBucket: 'leafyyy-6ccee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwNroXLTJQygObqGEHLlZX6il4-4J6SPQ',
    appId: '1:1073665114674:ios:1e7fb02eb0b01b1016b22b',
    messagingSenderId: '1073665114674',
    projectId: 'leafyyy-6ccee',
    storageBucket: 'leafyyy-6ccee.appspot.com',
    iosBundleId: 'com.example.leafycamera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwNroXLTJQygObqGEHLlZX6il4-4J6SPQ',
    appId: '1:1073665114674:ios:392879d432bd893916b22b',
    messagingSenderId: '1073665114674',
    projectId: 'leafyyy-6ccee',
    storageBucket: 'leafyyy-6ccee.appspot.com',
    iosBundleId: 'com.example.leafycamera.RunnerTests',
  );
}
